### ISSUE TITLE
[PDF] Typo page 16 line 5

### ISSUE THREAD

**Issue by pi3r** [patshaughnessy/ruby-under-a-microscope#1]
`Tokenization and parsing are two separate processes that actually happen at the time time` should be `Tokenization and parsing are two separate processes that actually happen at the same time`

**Comment by patshaughnessy** [comment]
Fixed! Thanks a lot for reporting this! I'll update the download kit tomorrow. You'll get an email, and will be able to download the updated version of the book if you'd like. New readers will get the fixed version.
