### ISSUE TITLE
[PDF] Typo - page 19

### ISSUE THREAD

**Issue by ghost** [patshaughnessy/ruby-under-a-microscope#2]
### Final paragraph
- They may have done this for performance reasons, or because Ruby’s tokenization rules required special logic Lex **could’t** provide.

**Comment by patshaughnessy** [comment]
Fixed! Thanks a lot for this. I'll update the download kit tomorrow. You'll get an email, and will be able to download the updated version of the book if you'd like. New readers will get the fixed version.
